# Generated by Django 5.1.15 on 2026-04-11 13:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('OD', 'Odontologia'), ('PS', 'Psicologia'), ('FI', 'Fisioterapia'), ('EN', 'Enfermagem')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('EM_ESPERA', 'Em Espera'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('AGUARDANDO_SUPERVISOR', 'Aguardando Supervisor'), ('CONCLUIDO', 'Concluído')], default='CONFIRMADO', max_length=25)),
                ('academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_core.academico')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_core.paciente')),
            ],
        ),
    ]
