# Generated by Django 5.1.15 on 2026-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0002_academico_date_alter_academico_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaespera',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
