# Generated by Django 5.1.15 on 2026-04-16 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0005_paciente_celular_paciente_cpf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_alter', models.DateTimeField(auto_now=True, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('historico_medico', models.TextField(blank=True, null=True, verbose_name='Histórico Médico')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('pressao_arterial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pressão Arterial')),
                ('medicamentos_em_uso', models.TextField(blank=True, null=True, verbose_name='Medicamentos em Uso')),
                ('queixa_principal', models.TextField(blank=True, null=True, verbose_name='Queixa Principal')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='clinica_core.paciente')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
