# Generated by Django 5.1.15 on 2026-04-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0009_alter_evolucao_options_academico_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaespera',
            name='clinica_odonto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='clinica_core.clinicaodonto'),
        ),
    ]
