# Generated by Django 5.1.15 on 2026-04-16 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0010_listaespera_clinica_odonto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplaOdonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_alter', models.DateTimeField(auto_now=True, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sufixo ou Identificador (Opcional)')),
                ('aluno1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplas_primarias', to='clinica_core.academico', verbose_name='Aluno/Acadêmico 1 (Titular)')),
                ('aluno2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplas_secundarias', to='clinica_core.academico', verbose_name='Aluno/Acadêmico 2 (Opcional)')),
                ('clinica_odonto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplas', to='clinica_core.clinicaodonto', verbose_name='Sub-Clínica/Turma')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
