# Generated by Django 5.1.15 on 2026-04-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0011_duplaodonto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlteracaoEvolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('nota_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_nova', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('observacao_anterior', models.TextField(blank=True, null=True)),
                ('observacao_nova', models.TextField(blank=True, null=True)),
                ('evolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_alteracao', to='clinica_core.evolucao')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica_core.professor')),
            ],
        ),
    ]
