# Generated by Django 5.1.15 on 2026-04-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0012_logalteracaoevolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacao',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_core.professor', verbose_name='Professor/Responsável'),
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_core.academico'),
        ),
    ]
