# Generated by Django 5.1.15 on 2026-04-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0015_marcacao_data_hora_finalizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='clinica_core.clinica'),
        ),
        migrations.AddField(
            model_name='documentopaciente',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clinica_core.clinica'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='clinica_core.clinica'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='clinica_core.paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='anamnese',
            unique_together={('paciente', 'clinica')},
        ),
    ]
