# Generated by Django 5.1.15 on 2026-04-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0016_anamnese_clinica_documentopaciente_clinica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaespera',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('AGENDADO', 'Agendado'), ('CONCLUÍDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_alter', models.DateTimeField(auto_now=True, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Box / Sala')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='clinica_core.clinica', verbose_name='Clínica')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Box / Sala',
                'verbose_name_plural': 'Boxes / Salas',
                'ordering': ['clinica', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='marcacao',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes', to='clinica_core.box', verbose_name='Box / Sala'),
        ),
    ]
