# Generated by Django 5.1.15 on 2026-04-23 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0017_alter_listaespera_status_box_marcacao_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacao',
            name='lista_espera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes', to='clinica_core.listaespera', verbose_name='Origem (Lista de Espera)'),
        ),
    ]
