# Generated by Django 5.1.15 on 2026-04-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0018_marcacao_lista_espera'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaespera',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_lista_espera', to='clinica_core.marcacao', verbose_name='Agendamento gerado'),
        ),
    ]
