# Generated by Django 5.1.15 on 2026-04-27 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_core', '0020_itemestoque_movimentacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacao',
            name='dupla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes', to='clinica_core.duplaodonto', verbose_name='Dupla de Alunos (Odonto)'),
        ),
    ]
